name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.15.3'
    # setup yarn cache
    - name: Cache yarn
      uses: actions/cache@v1
      env:
        cache-name: cache-yarn
      with:
        path: ~/.cache/yarn
        key: yarn-${{ hashFiles('yarn.lock') }}
    # install deps
    - name: Install dependencies
      run: yarn install --cache-folder ~/.cache/yarn
    # client dotenv
    - name: Client dotenv
      run: 'echo "$DOTENV" > client/.env.production'
      shell: bash
      env:
        DOTENV: ${{secrets.DOTENV_CLIENT}}
    # build
    - name: Build
      run: yarn build
    # copy to deploy dir
    - name: Create clean deploy dir
      run: |
        mkdir deploy
        cp package.json deploy
        cp yarn.lock deploy
        cp app.yaml deploy
        cp .gcloudignore deploy
        mkdir deploy/client
        mkdir deploy/server
        cp -r ./client/dist deploy/client
        cp -r ./server/build deploy/server
    # server dotenv
    - name: Server dotenv
      run: 'echo "$DOTENV" > deploy/.env'
      shell: bash
      env:
        DOTENV: ${{secrets.DOTENV_SERVER}}
    # setup gcloud
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '281.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Set glcoud project
      run: gcloud config set project ${{ secrets.GCP_PROJECT }}
    # deploy
    - name: Deploy
      run: gcloud app deploy -q deploy/app.yaml
